FROM debian:jessie
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    curl \
    devscripts \
    libtool \
    make \
    texinfo

# compile and install liblouis
WORKDIR /usr/src/
RUN curl -L https://github.com/liblouis/liblouis/archive/liblouis_2_5_2.tar.gz | tar zx
WORKDIR /usr/src/liblouis-liblouis_2_5_2/
RUN ./autogen.sh && \
    ./configure --enable-ucs4 && \
    make && \
    make install && \
    ldconfig

# build braille tables
ADD . /usr/src/liblouis
WORKDIR /usr/src/liblouis
RUN debuild -us -uc -b -d


