@echo off
call tab2lou sbs.dis_src                     ..\..\tables\sbs.dis
call tab2lou sbs-de-accents.cti_src          ..\..\tables\sbs-de-accents.cti
call tab2lou sbs-de-accents.mod_src          ..\..\tables\sbs-de-accents.mod
call tab2lou sbs-de-accents-ch.mod_src       ..\..\tables\sbs-de-accents-ch.mod
call tab2lou sbs-de-accents-reduced.mod_src  ..\..\tables\sbs-de-accents-reduced.mod
call tab2lou sbs-de-begendcaps.mod_src       ..\..\tables\sbs-de-begendcaps.mod
call tab2lou sbs-de-capsign.mod_src          ..\..\tables\sbs-de-capsign.mod
call tab2lou sbs-de-core.mod_src             ..\..\tables\sbs-de-core.mod
call tab2lou sbs-de-core6.cti_src            ..\..\tables\sbs-de-core6.cti
call tab2lou sbs-de-g0-core.mod_src          ..\..\tables\sbs-de-g0-core.mod
call tab2lou sbs-de-g1-core.mod_src          ..\..\tables\sbs-de-g1-core.mod
call tab2lou sbs-de-g2-core.mod_src          ..\..\tables\sbs-de-g2-core.mod
call tab2lou sbs-de-g2-name.mod_src          ..\..\tables\sbs-de-g2-name.mod
call tab2lou sbs-de-g2-place.mod_src         ..\..\tables\sbs-de-g2-place.mod
call tab2lou sbs-de-hyph-new.mod_src         ..\..\tables\sbs-de-hyph-new.mod
call tab2lou sbs-de-hyph-none.mod_src        ..\..\tables\sbs-de-hyph-none.mod
call tab2lou sbs-de-hyph-old.mod_src         ..\..\tables\sbs-de-hyph-old.mod
call tab2lou sbs-de-hyph-word.mod_src        ..\..\tables\sbs-de-hyph-word.mod
call tab2lou sbs-de-letsign.mod_src          ..\..\tables\sbs-de-letsign.mod
call tab2lou sbs-litdigit-lower.mod_src      ..\..\tables\sbs-litdigit-lower.mod
call tab2lou sbs-litdigit-upper.mod_src      ..\..\tables\sbs-litdigit-upper.mod
call tab2lou sbs-numsign.mod_src             ..\..\tables\sbs-numsign.mod
call tab2lou sbs-special.cti_src             ..\..\tables\sbs-special.cti
call tab2lou sbs-special.mod_src             ..\..\tables\sbs-special.mod
call tab2lou sbs-whitespace.mod_src          ..\..\tables\sbs-whitespace.mod
